### DISCUSSION TITLE
How to increase stacksize?

### DISCUSSION THREAD

**Discussion by evbo** [aws/aws-lambda-rust-runtime#814] [Q&A]
If I create a `.cargo` folder in my project root and place in it `config.toml` with:

```toml
[build]
rustflags = [
    "-C", "link-arg=-zstack-size=104857600"
]

```

Will the lambda execute my Rust program with 10MB of stacksize?
